<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	Country::truncate();
        $countries = array(
			array('id' => 1,'short_code' => 'AF' ,'name' => "Afghanistan",'phone_code' => 93),
			array('id' => 2,'short_code' => 'AL' ,'name' => "Albania",'phone_code' => 355),
			array('id' => 3,'short_code' => 'DZ' ,'name' => "Algeria",'phone_code' => 213),
			array('id' => 4,'short_code' => 'AS' ,'name' => "American Samoa",'phone_code' => 1684),
			array('id' => 5,'short_code' => 'AD' ,'name' => "Andorra",'phone_code' => 376),
			array('id' => 6,'short_code' => 'AO' ,'name' => "Angola",'phone_code' => 244),
			array('id' => 7,'short_code' => 'AI' ,'name' => "Anguilla",'phone_code' => 1264),
			array('id' => 8,'short_code' => 'AQ' ,'name' => "Antarctica",'phone_code' => 0),
			array('id' => 9,'short_code' => 'AG' ,'name' => "Antigua And Barbuda",'phone_code' => 1268),
			array('id' => 10,'short_code' => 'AR','name' => "Argentina",'phone_code' => 54),
			array('id' => 11,'short_code' => 'AM','name' => "Armenia",'phone_code' => 374),
			array('id' => 12,'short_code' => 'AW','name' => "Aruba",'phone_code' => 297),
			array('id' => 13,'short_code' => 'AU','name' => "Australia",'phone_code' => 61),
			array('id' => 14,'short_code' => 'AT','name' => "Austria",'phone_code' => 43),
			array('id' => 15,'short_code' => 'AZ','name' => "Azerbaijan",'phone_code' => 994),
			array('id' => 16,'short_code' => 'BS','name' => "Bahamas The",'phone_code' => 1242),
			array('id' => 17,'short_code' => 'BH','name' => "Bahrain",'phone_code' => 973),
			array('id' => 18,'short_code' => 'BD','name' => "Bangladesh",'phone_code' => 880),
			array('id' => 19,'short_code' => 'BB','name' => "Barbados",'phone_code' => 1246),
			array('id' => 20,'short_code' => 'BY','name' => "Belarus",'phone_code' => 375),
			array('id' => 21,'short_code' => 'BE','name' => "Belgium",'phone_code' => 32),
			array('id' => 22,'short_code' => 'BZ','name' => "Belize",'phone_code' => 501),
			array('id' => 23,'short_code' => 'BJ','name' => "Benin",'phone_code' => 229),
			array('id' => 24,'short_code' => 'BM','name' => "Bermuda",'phone_code' => 1441),
			array('id' => 25,'short_code' => 'BT','name' => "Bhutan",'phone_code' => 975),
			array('id' => 26,'short_code' => 'BO','name' => "Bolivia",'phone_code' => 591),
			array('id' => 27,'short_code' => 'BA','name' => "Bosnia and Herzegovina",'phone_code' => 387),
			array('id' => 28,'short_code' => 'BW','name' => "Botswana",'phone_code' => 267),
			array('id' => 29,'short_code' => 'BV','name' => "Bouvet Island",'phone_code' => 0),
			array('id' => 30,'short_code' => 'BR','name' => "Brazil",'phone_code' => 55),
			array('id' => 31,'short_code' => 'IO','name' => "British Indian Ocean Territory",'phone_code' => 246),
			array('id' => 32,'short_code' => 'BN','name' => "Brunei",'phone_code' => 673),
			array('id' => 33,'short_code' => 'BG','name' => "Bulgaria",'phone_code' => 359),
			array('id' => 34,'short_code' => 'BF','name' => "Burkina Faso",'phone_code' => 226),
			array('id' => 35,'short_code' => 'BI','name' => "Burundi",'phone_code' => 257),
			array('id' => 36,'short_code' => 'KH','name' => "Cambodia",'phone_code' => 855),
			array('id' => 37,'short_code' => 'CM','name' => "Cameroon",'phone_code' => 237),
			array('id' => 38,'short_code' => 'CA','name' => "Canada",'phone_code' => 1),
			array('id' => 39,'short_code' => 'CV','name' => "Cape Verde",'phone_code' => 238),
			array('id' => 40,'short_code' => 'KY','name' => "Cayman Islands",'phone_code' => 1345),
			array('id' => 41,'short_code' => 'CF','name' => "Central African Republic",'phone_code' => 236),
			array('id' => 42,'short_code' => 'TD','name' => "Chad",'phone_code' => 235),
			array('id' => 43,'short_code' => 'CL','name' => "Chile",'phone_code' => 56),
			array('id' => 44,'short_code' => 'CN','name' => "China",'phone_code' => 86),
			array('id' => 45,'short_code' => 'CX','name' => "Christmas Island",'phone_code' => 61),
			array('id' => 46,'short_code' => 'CC','name' => "Cocos (Keeling) Islands",'phone_code' => 672),
			array('id' => 47,'short_code' => 'CO','name' => "Colombia",'phone_code' => 57),
			array('id' => 48,'short_code' => 'KM','name' => "Comoros",'phone_code' => 269),
			array('id' => 49,'short_code' => 'CG','name' => "Congo",'phone_code' => 242),
			array('id' => 50,'short_code' => 'CD','name' => "Congo The Democratic Republic Of The",'phone_code' => 242),
			array('id' => 51,'short_code' => 'CK','name' => "Cook Islands",'phone_code' => 682),
			array('id' => 52,'short_code' => 'CR','name' => "Costa Rica",'phone_code' => 506),
			array('id' => 53,'short_code' => 'CI','name' => "Cote D Ivoire (Ivory Coast)",'phone_code' => 225),
			array('id' => 54,'short_code' => 'HR','name' => "Croatia (Hrvatska)",'phone_code' => 385),
			array('id' => 55,'short_code' => 'CU','name' => "Cuba",'phone_code' => 53),
			array('id' => 56,'short_code' => 'CY','name' => "Cyprus",'phone_code' => 357),
			array('id' => 57,'short_code' => 'CZ','name' => "Czech Republic",'phone_code' => 420),
			array('id' => 58,'short_code' => 'DK','name' => "Denmark",'phone_code' => 45),
			array('id' => 59,'short_code' => 'DJ','name' => "Djibouti",'phone_code' => 253),
			array('id' => 60,'short_code' => 'DM','name' => "Dominica",'phone_code' => 1767),
			array('id' => 61,'short_code' => 'DO','name' => "Dominican Republic",'phone_code' => 1809),
			array('id' => 62,'short_code' => 'TP','name' => "East Timor",'phone_code' => 670),
			array('id' => 63,'short_code' => 'EC','name' => "Ecuador",'phone_code' => 593),
			array('id' => 64,'short_code' => 'EG','name' => "Egypt",'phone_code' => 20),
			array('id' => 65,'short_code' => 'SV','name' => "El Salvador",'phone_code' => 503),
			array('id' => 66,'short_code' => 'GQ','name' => "Equatorial Guinea",'phone_code' => 240),
			array('id' => 67,'short_code' => 'ER','name' => "Eritrea",'phone_code' => 291),
			array('id' => 68,'short_code' => 'EE','name' => "Estonia",'phone_code' => 372),
			array('id' => 69,'short_code' => 'ET','name' => "Ethiopia",'phone_code' => 251),
			array('id' => 70,'short_code' => 'XA','name' => "External Territories of Australia",'phone_code' => 61),
			array('id' => 71,'short_code' => 'FK','name' => "Falkland Islands",'phone_code' => 500),
			array('id' => 72,'short_code' => 'FO','name' => "Faroe Islands",'phone_code' => 298),
			array('id' => 73,'short_code' => 'FJ','name' => "Fiji Islands",'phone_code' => 679),
			array('id' => 74,'short_code' => 'FI','name' => "Finland",'phone_code' => 358),
			array('id' => 75,'short_code' => 'FR','name' => "France",'phone_code' => 33),
			array('id' => 76,'short_code' => 'GF','name' => "French Guiana",'phone_code' => 594),
			array('id' => 77,'short_code' => 'PF','name' => "French Polynesia",'phone_code' => 689),
			array('id' => 78,'short_code' => 'TF','name' => "French Southern Territories",'phone_code' => 0),
			array('id' => 79,'short_code' => 'GA','name' => "Gabon",'phone_code' => 241),
			array('id' => 80,'short_code' => 'GM','name' => "Gambia The",'phone_code' => 220),
			array('id' => 81,'short_code' => 'GE','name' => "Georgia",'phone_code' => 995),
			array('id' => 82,'short_code' => 'DE','name' => "Germany",'phone_code' => 49),
			array('id' => 83,'short_code' => 'GH','name' => "Ghana",'phone_code' => 233),
			array('id' => 84,'short_code' => 'GI','name' => "Gibraltar",'phone_code' => 350),
			array('id' => 85,'short_code' => 'GR','name' => "Greece",'phone_code' => 30),
			array('id' => 86,'short_code' => 'GL','name' => "Greenland",'phone_code' => 299),
			array('id' => 87,'short_code' => 'GD','name' => "Grenada",'phone_code' => 1473),
			array('id' => 88,'short_code' => 'GP','name' => "Guadeloupe",'phone_code' => 590),
			array('id' => 89,'short_code' => 'GU','name' => "Guam",'phone_code' => 1671),
			array('id' => 90,'short_code' => 'GT','name' => "Guatemala",'phone_code' => 502),
			array('id' => 91,'short_code' => 'XU','name' => "Guernsey and Alderney",'phone_code' => 44),
			array('id' => 92,'short_code' => 'GN','name' => "Guinea",'phone_code' => 224),
			array('id' => 93,'short_code' => 'GW','name' => "Guinea-Bissau",'phone_code' => 245),
			array('id' => 94,'short_code' => 'GY','name' => "Guyana",'phone_code' => 592),
			array('id' => 95,'short_code' => 'HT','name' => "Haiti",'phone_code' => 509),
			array('id' => 96,'short_code' => 'HM','name' => "Heard and McDonald Islands",'phone_code' => 0),
			array('id' => 97,'short_code' => 'HN','name' => "Honduras",'phone_code' => 504),
			array('id' => 98,'short_code' => 'HK','name' => "Hong Kong S.A.R.",'phone_code' => 852),
			array('id' => 99,'short_code' => 'HU','name' => "Hungary",'phone_code' => 36),
			array('id' => 100,'short_code' => 'IS','name' => "Iceland",'phone_code' => 354),
			array('id' => 101,'short_code' => 'IN','name' => "India",'phone_code' => 91),
			array('id' => 102,'short_code' => 'ID','name' => "Indonesia",'phone_code' => 62),
			array('id' => 103,'short_code' => 'IR','name' => "Iran",'phone_code' => 98),
			array('id' => 104,'short_code' => 'IQ','name' => "Iraq",'phone_code' => 964),
			array('id' => 105,'short_code' => 'IE','name' => "Ireland",'phone_code' => 353),
			array('id' => 106,'short_code' => 'IL','name' => "Israel",'phone_code' => 972),
			array('id' => 107,'short_code' => 'IT','name' => "Italy",'phone_code' => 39),
			array('id' => 108,'short_code' => 'JM','name' => "Jamaica",'phone_code' => 1876),
			array('id' => 109,'short_code' => 'JP','name' => "Japan",'phone_code' => 81),
			array('id' => 110,'short_code' => 'XJ','name' => "Jersey",'phone_code' => 44),
			array('id' => 111,'short_code' => 'JO','name' => "Jordan",'phone_code' => 962),
			array('id' => 112,'short_code' => 'KZ','name' => "Kazakhstan",'phone_code' => 7),
			array('id' => 113,'short_code' => 'KE','name' => "Kenya",'phone_code' => 254),
			array('id' => 114,'short_code' => 'KI','name' => "Kiribati",'phone_code' => 686),
			array('id' => 115,'short_code' => 'KP','name' => "Korea North",'phone_code' => 850),
			array('id' => 116,'short_code' => 'KR','name' => "Korea South",'phone_code' => 82),
			array('id' => 117,'short_code' => 'KW','name' => "Kuwait",'phone_code' => 965),
			array('id' => 118,'short_code' => 'KG','name' => "Kyrgyzstan",'phone_code' => 996),
			array('id' => 119,'short_code' => 'LA','name' => "Laos",'phone_code' => 856),
			array('id' => 120,'short_code' => 'LV','name' => "Latvia",'phone_code' => 371),
			array('id' => 121,'short_code' => 'LB','name' => "Lebanon",'phone_code' => 961),
			array('id' => 122,'short_code' => 'LS','name' => "Lesotho",'phone_code' => 266),
			array('id' => 123,'short_code' => 'LR','name' => "Liberia",'phone_code' => 231),
			array('id' => 124,'short_code' => 'LY','name' => "Libya",'phone_code' => 218),
			array('id' => 125,'short_code' => 'LI','name' => "Liechtenstein",'phone_code' => 423),
			array('id' => 126,'short_code' => 'LT','name' => "Lithuania",'phone_code' => 370),
			array('id' => 127,'short_code' => 'LU','name' => "Luxembourg",'phone_code' => 352),
			array('id' => 128,'short_code' => 'MO','name' => "Macau S.A.R.",'phone_code' => 853),
			array('id' => 129,'short_code' => 'MK','name' => "Macedonia",'phone_code' => 389),
			array('id' => 130,'short_code' => 'MG','name' => "Madagascar",'phone_code' => 261),
			array('id' => 131,'short_code' => 'MW','name' => "Malawi",'phone_code' => 265),
			array('id' => 132,'short_code' => 'MY','name' => "Malaysia",'phone_code' => 60),
			array('id' => 133,'short_code' => 'MV','name' => "Maldives",'phone_code' => 960),
			array('id' => 134,'short_code' => 'ML','name' => "Mali",'phone_code' => 223),
			array('id' => 135,'short_code' => 'MT','name' => "Malta",'phone_code' => 356),
			array('id' => 136,'short_code' => 'XM','name' => "Man (Isle of)",'phone_code' => 44),
			array('id' => 137,'short_code' => 'MH','name' => "Marshall Islands",'phone_code' => 692),
			array('id' => 138,'short_code' => 'MQ','name' => "Martinique",'phone_code' => 596),
			array('id' => 139,'short_code' => 'MR','name' => "Mauritania",'phone_code' => 222),
			array('id' => 140,'short_code' => 'MU','name' => "Mauritius",'phone_code' => 230),
			array('id' => 141,'short_code' => 'YT','name' => "Mayotte",'phone_code' => 269),
			array('id' => 142,'short_code' => 'MX','name' => "Mexico",'phone_code' => 52),
			array('id' => 143,'short_code' => 'FM','name' => "Micronesia",'phone_code' => 691),
			array('id' => 144,'short_code' => 'MD','name' => "Moldova",'phone_code' => 373),
			array('id' => 145,'short_code' => 'MC','name' => "Monaco",'phone_code' => 377),
			array('id' => 146,'short_code' => 'MN','name' => "Mongolia",'phone_code' => 976),
			array('id' => 147,'short_code' => 'MS','name' => "Montserrat",'phone_code' => 1664),
			array('id' => 148,'short_code' => 'MA','name' => "Morocco",'phone_code' => 212),
			array('id' => 149,'short_code' => 'MZ','name' => "Mozambique",'phone_code' => 258),
			array('id' => 150,'short_code' => 'MM','name' => "Myanmar",'phone_code' => 95),
			array('id' => 151,'short_code' => 'NA','name' => "Namibia",'phone_code' => 264),
			array('id' => 152,'short_code' => 'NR','name' => "Nauru",'phone_code' => 674),
			array('id' => 153,'short_code' => 'NP','name' => "Nepal",'phone_code' => 977),
			array('id' => 154,'short_code' => 'AN','name' => "Netherlands Antilles",'phone_code' => 599),
			array('id' => 155,'short_code' => 'NL','name' => "Netherlands The",'phone_code' => 31),
			array('id' => 156,'short_code' => 'NC','name' => "New Caledonia",'phone_code' => 687),
			array('id' => 157,'short_code' => 'NZ','name' => "New Zealand",'phone_code' => 64),
			array('id' => 158,'short_code' => 'NI','name' => "Nicaragua",'phone_code' => 505),
			array('id' => 159,'short_code' => 'NE','name' => "Niger",'phone_code' => 227),
			array('id' => 160,'short_code' => 'NG','name' => "Nigeria",'phone_code' => 234),
			array('id' => 161,'short_code' => 'NU','name' => "Niue",'phone_code' => 683),
			array('id' => 162,'short_code' => 'NF','name' => "Norfolk Island",'phone_code' => 672),
			array('id' => 163,'short_code' => 'MP','name' => "Northern Mariana Islands",'phone_code' => 1670),
			array('id' => 164,'short_code' => 'NO','name' => "Norway",'phone_code' => 47),
			array('id' => 165,'short_code' => 'OM','name' => "Oman",'phone_code' => 968),
			array('id' => 166,'short_code' => 'PK','name' => "Pakistan",'phone_code' => 92),
			array('id' => 167,'short_code' => 'PW','name' => "Palau",'phone_code' => 680),
			array('id' => 168,'short_code' => 'PS','name' => "Palestinian Territory Occupied",'phone_code' => 970),
			array('id' => 169,'short_code' => 'PA','name' => "Panama",'phone_code' => 507),
			array('id' => 170,'short_code' => 'PG','name' => "Papua new Guinea",'phone_code' => 675),
			array('id' => 171,'short_code' => 'PY','name' => "Paraguay",'phone_code' => 595),
			array('id' => 172,'short_code' => 'PE','name' => "Peru",'phone_code' => 51),
			array('id' => 173,'short_code' => 'PH','name' => "Philippines",'phone_code' => 63),
			array('id' => 174,'short_code' => 'PN','name' => "Pitcairn Island",'phone_code' => 0),
			array('id' => 175,'short_code' => 'PL','name' => "Poland",'phone_code' => 48),
			array('id' => 176,'short_code' => 'PT','name' => "Portugal",'phone_code' => 351),
			array('id' => 177,'short_code' => 'PR','name' => "Puerto Rico",'phone_code' => 1787),
			array('id' => 178,'short_code' => 'QA','name' => "Qatar",'phone_code' => 974),
			array('id' => 179,'short_code' => 'RE','name' => "Reunion",'phone_code' => 262),
			array('id' => 180,'short_code' => 'RO','name' => "Romania",'phone_code' => 40),
			array('id' => 181,'short_code' => 'RU','name' => "Russia",'phone_code' => 70),
			array('id' => 182,'short_code' => 'RW','name' => "Rwanda",'phone_code' => 250),
			array('id' => 183,'short_code' => 'SH','name' => "Saint Helena",'phone_code' => 290),
			array('id' => 184,'short_code' => 'KN','name' => "Saint Kitts And Nevis",'phone_code' => 1869),
			array('id' => 185,'short_code' => 'LC','name' => "Saint Lucia",'phone_code' => 1758),
			array('id' => 186,'short_code' => 'PM','name' => "Saint Pierre and Miquelon",'phone_code' => 508),
			array('id' => 187,'short_code' => 'VC','name' => "Saint Vincent And The Grenadines",'phone_code' => 1784),
			array('id' => 188,'short_code' => 'WS','name' => "Samoa",'phone_code' => 684),
			array('id' => 189,'short_code' => 'SM','name' => "San Marino",'phone_code' => 378),
			array('id' => 190,'short_code' => 'ST','name' => "Sao Tome and Principe",'phone_code' => 239),
			array('id' => 191,'short_code' => 'SA','name' => "Saudi Arabia",'phone_code' => 966),
			array('id' => 192,'short_code' => 'SN','name' => "Senegal",'phone_code' => 221),
			array('id' => 193,'short_code' => 'RS','name' => "Serbia",'phone_code' => 381),
			array('id' => 194,'short_code' => 'SC','name' => "Seychelles",'phone_code' => 248),
			array('id' => 195,'short_code' => 'SL','name' => "Sierra Leone",'phone_code' => 232),
			array('id' => 196,'short_code' => 'SG','name' => "Singapore",'phone_code' => 65),
			array('id' => 197,'short_code' => 'SK','name' => "Slovakia",'phone_code' => 421),
			array('id' => 198,'short_code' => 'SI','name' => "Slovenia",'phone_code' => 386),
			array('id' => 199,'short_code' => 'XG','name' => "Smaller Territories of the UK",'phone_code' => 44),
			array('id' => 200,'short_code' => 'SB','name' => "Solomon Islands",'phone_code' => 677),
			array('id' => 201,'short_code' => 'SO','name' => "Somalia",'phone_code' => 252),
			array('id' => 202,'short_code' => 'ZA','name' => "South Africa",'phone_code' => 27),
			array('id' => 203,'short_code' => 'GS','name' => "South Georgia",'phone_code' => 0),
			array('id' => 204,'short_code' => 'SS','name' => "South Sudan",'phone_code' => 211),
			array('id' => 205,'short_code' => 'ES','name' => "Spain",'phone_code' => 34),
			array('id' => 206,'short_code' => 'LK','name' => "Sri Lanka",'phone_code' => 94),
			array('id' => 207,'short_code' => 'SD','name' => "Sudan",'phone_code' => 249),
			array('id' => 208,'short_code' => 'SR','name' => "Suriname",'phone_code' => 597),
			array('id' => 209,'short_code' => 'SJ','name' => "Svalbard And Jan Mayen Islands",'phone_code' => 47),
			array('id' => 210,'short_code' => 'SZ','name' => "Swaziland",'phone_code' => 268),
			array('id' => 211,'short_code' => 'SE','name' => "Sweden",'phone_code' => 46),
			array('id' => 212,'short_code' => 'CH','name' => "Switzerland",'phone_code' => 41),
			array('id' => 213,'short_code' => 'SY','name' => "Syria",'phone_code' => 963),
			array('id' => 214,'short_code' => 'TW','name' => "Taiwan",'phone_code' => 886),
			array('id' => 215,'short_code' => 'TJ','name' => "Tajikistan",'phone_code' => 992),
			array('id' => 216,'short_code' => 'TZ','name' => "Tanzania",'phone_code' => 255),
			array('id' => 217,'short_code' => 'TH','name' => "Thailand",'phone_code' => 66),
			array('id' => 218,'short_code' => 'TG','name' => "Togo",'phone_code' => 228),
			array('id' => 219,'short_code' => 'TK','name' => "Tokelau",'phone_code' => 690),
			array('id' => 220,'short_code' => 'TO','name' => "Tonga",'phone_code' => 676),
			array('id' => 221,'short_code' => 'TT','name' => "Trinidad And Tobago",'phone_code' => 1868),
			array('id' => 222,'short_code' => 'TN','name' => "Tunisia",'phone_code' => 216),
			array('id' => 223,'short_code' => 'TR','name' => "Turkey",'phone_code' => 90),
			array('id' => 224,'short_code' => 'TM','name' => "Turkmenistan",'phone_code' => 7370),
			array('id' => 225,'short_code' => 'TC','name' => "Turks And Caicos Islands",'phone_code' => 1649),
			array('id' => 226,'short_code' => 'TV','name' => "Tuvalu",'phone_code' => 688),
			array('id' => 227,'short_code' => 'UG','name' => "Uganda",'phone_code' => 256),
			array('id' => 228,'short_code' => 'UA','name' => "Ukraine",'phone_code' => 380),
			array('id' => 229,'short_code' => 'AE','name' => "United Arab Emirates",'phone_code' => 971),
			array('id' => 230,'short_code' => 'GB','name' => "United Kingdom",'phone_code' => 44),
			array('id' => 231,'short_code' => 'US','name' => "United States",'phone_code' => 1),
			array('id' => 232,'short_code' => 'UM','name' => "United States Minor Outlying Islands",'phone_code' => 1),
			array('id' => 233,'short_code' => 'UY','name' => "Uruguay",'phone_code' => 598),
			array('id' => 234,'short_code' => 'UZ','name' => "Uzbekistan",'phone_code' => 998),
			array('id' => 235,'short_code' => 'VU','name' => "Vanuatu",'phone_code' => 678),
			array('id' => 236,'short_code' => 'VA','name' => "Vatican City State (Holy See)",'phone_code' => 39),
			array('id' => 237,'short_code' => 'VE','name' => "Venezuela",'phone_code' => 58),
			array('id' => 238,'short_code' => 'VN','name' => "Vietnam",'phone_code' => 84),
			array('id' => 239,'short_code' => 'VG','name' => "Virgin Islands (British)",'phone_code' => 1284),
			array('id' => 240,'short_code' => 'VI','name' => "Virgin Islands (US)",'phone_code' => 1340),
			array('id' => 241,'short_code' => 'WF','name' => "Wallis And Futuna Islands",'phone_code' => 681),
			array('id' => 242,'short_code' => 'EH','name' => "Western Sahara",'phone_code' => 212),
			array('id' => 243,'short_code' => 'YE','name' => "Yemen",'phone_code' => 967),
			array('id' => 244,'short_code' => 'YU','name' => "Yugoslavia",'phone_code' => 38),
			array('id' => 245,'short_code' => 'ZM','name' => "Zambia",'phone_code' => 260),
			array('id' => 246,'short_code' => 'ZW','name' => "Zimbabwe",'phone_code' => 263),
		);

		Country::insert($countries);
    }
}
