<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use App\Models\Currency;
class CurrencyTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	Currency::truncate();
        $currencies = [
			['currency' =>'AFN' , 'name' => 'Afghani', 'symbol' => '؋' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'ALL' , 'name' => 'Lek', 'symbol' => 'Lek' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'ANG' , 'name' => 'Netherlands Antillian Guilder', 'symbol' => 'ƒ' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'ARS' , 'name' => 'Argentine Peso', 'symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'AUD' , 'name' => 'Australian Dollar', 'symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'AWG' , 'name' => 'Aruban Guilder', 'symbol' => 'ƒ' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'AZN' , 'name' => 'Azerbaijanian Manat', 'symbol' => 'ман' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'BAM' , 'name' => 'Convertible Marks', 'symbol' => 'KM' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'BBD' , 'name' => 'Barbados Dollar', 'symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'BGN' , 'name' => 'Bulgarian Lev', 'symbol' => 'лв' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'BMD' , 'name' => 'Bermudian Dollar', 'symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'BND' , 'name' => 'Brunei Dollar', 'symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'BOB' , 'name' => 'BOV Boliviano Mvdol', 'symbol' => '$b' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'BRL' , 'name' => 'Brazilian Real', 'symbol' => 'R$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'BSD' , 'name' => 'Bahamian Dollar', 'symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'BWP' , 'name' => 'Pula', 'symbol' => 'P' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'BYR' , 'name' => 'Belarussian Ruble', 'symbol' => 'p.' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'BZD' , 'name' => 'Belize Dollar', 'symbol' => 'BZ$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'CAD' , 'name' => 'Canadian Dollar', 'symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'CHF' , 'name' => 'Swiss Franc', 'symbol' => 'CHF' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'CLP' , 'name' => 'CLF Chilean Peso Unidades de fomento', 'symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'CNY' , 'name' => 'Yuan Renminbi', 'symbol' => '¥' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'COP' , 'name' => 'COU Colombian Peso Unidad de Valor Real', 'symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'CRC' , 'name' => 'Costa Rican Colon', 'symbol' => '₡' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'CUP' , 'name' => 'CUC Cuban Peso Peso Convertible', 'symbol' => '₱' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'CZK' , 'name' => 'Czech Koruna', 'symbol' => 'Kč' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'DKK' , 'name' => 'Danish Krone', 'symbol' => 'kr' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'DOP' , 'name' => 'Dominican Peso', 'symbol' => 'RD$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'EGP' , 'name' => 'Egyptian Pound', 'symbol' => '£' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'EUR' , 'name' => 'Euro', 'symbol' => '€' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'FJD' , 'name' => 'Fiji Dollar', 'symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'FKP' , 'name' => 'Falkland Islands Pound', 'symbol' => '£' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'GBP' , 'name' => 'Pound Sterling', 'symbol' => '£' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'GIP' , 'name' => 'Gibraltar Pound', 'symbol' => '£' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'GTQ' , 'name' => 'Quetzal', 'symbol' => 'Q' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'GYD' , 'name' => 'Guyana Dollar', 'symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'HKD' , 'name' => 'Hong Kong Dollar', 'symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'HNL' , 'name' => 'Lempira', 'symbol' => 'L' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'HRK' , 'name' => 'Croatian Kuna', 'symbol' => 'kn' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'HUF' , 'name' => 'Forint', 'symbol' => 'Ft' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'IDR' , 'name' => 'Rupiah', 'symbol' => 'Rp' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'ILS' , 'name' => 'New Israeli Sheqel', 'symbol' => '₪' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'IRR' , 'name' => 'Iranian Rial', 'symbol' => '﷼' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'ISK' , 'name' => 'Iceland Krona', 'symbol' => 'kr' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'INR' , 'name' => 'Indian rupee', 'symbol' => '₹' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'JMD' , 'name' => 'Jamaican Dollar', 'symbol' => 'J$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'JPY' , 'name' => 'Yen', 'symbol' => '¥' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'KGS' , 'name' => 'Som', 'symbol' => 'лв' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'KHR' , 'name' => 'Riel', 'symbol' => '៛' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'KPW' , 'name' => 'North Korean Won', 'symbol' => '₩' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'KRW' , 'name' => 'Won', 'symbol' => '₩' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'KYD' , 'name' => 'Cayman Islands Dollar', 'symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'KZT' , 'name' => 'Tenge', 'symbol' => 'лв' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'LAK' , 'name' => 'Kip', 'symbol' => '₭' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'LBP' , 'name' => 'Lebanese Pound', 'symbol' => '£' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'LKR' , 'name' => 'Sri Lanka Rupee', 'symbol' => '₨' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'LRD' , 'name' => 'Liberian Dollar', 'symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'LTL' , 'name' => 'Lithuanian Litas', 'symbol' => 'Lt' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'LVL' , 'name' => 'Latvian Lats', 'symbol' => 'Ls' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'MKD' , 'name' => 'Denar', 'symbol' => 'ден' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'MNT' , 'name' => 'Tugrik', 'symbol' => '₮' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'MUR' , 'name' => 'Mauritius Rupee', 'symbol' => '₨' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'MXN' , 'name' => 'Pesos', 'symbol' => '$', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'MYR' , 'name' => 'Malaysian Ringgit', 'symbol' => 'RM' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'MZN' , 'name' => 'Metical', 'symbol' => 'MT' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'NGN' , 'name' => 'Naira', 'symbol' => '₦' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'NIO' , 'name' => 'Cordoba Oro', 'symbol' => 'C$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'NOK' , 'name' => 'Norwegian Krone', 'symbol' => 'kr' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'NPR' , 'name' => 'Nepalese Rupee', 'symbol' => '₨' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'NZD' , 'name' => 'New Zealand Dollar', 'symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'OMR' , 'name' => 'Rial Omani', 'symbol' => '﷼' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'PAB' , 'name' => 'USD Balboa US Dollar', 'symbol' => 'B/.' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'PEN' , 'name' => 'Nuevo Sol', 'symbol' => 'S/.' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'PHP' , 'name' => 'Philippine Peso', 'symbol' => 'Php' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'PKR' , 'name' => 'Pakistan Rupee', 'symbol' => '₨' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'PLN' , 'name' => 'Zloty', 'symbol' => 'zł' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'PYG' , 'name' => 'Guarani', 'symbol' => 'Gs' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'QAR' , 'name' => 'Qatari Rial', 'symbol' => '﷼' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'RON' , 'name' => 'New Leu', 'symbol' => 'lei' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'RSD' , 'name' => 'Serbian Dinar', 'symbol' => 'Дин.' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'RUB' , 'name' => 'Russian Ruble', 'symbol' => 'руб' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'SAR' , 'name' => 'Saudi Riyal', 'symbol' => '﷼' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'SBD' , 'name' => 'Solomon Islands Dollar', 'symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'SCR' , 'name' => 'Seychelles Rupee', 'symbol' => '₨' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'SEK' , 'name' => 'Swedish Krona', 'symbol' => 'kr' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'SGD' , 'name' => 'Singapore Dollar', 'symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'SHP' , 'name' => 'Saint Helena Pound', 'symbol' => '£' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'SOS' , 'name' => 'Somali Shilling', 'symbol' => 'S' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'SRD' , 'name' => 'Surinam Dollar', 'symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'SVC' , 'name' => 'USD El Salvador Colon US Dollar', 'symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'SYP' , 'name' => 'Syrian Pound', 'symbol' => '£' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'THB' , 'name' => 'Baht', 'symbol' => '฿' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'TRY' , 'name' => 'Turkish Lira', 'symbol' => '₺' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'TTD' , 'name' => 'Trinidad and Tobago Dollar', 'symbol' => 'TT$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'TWD' , 'name' => 'New Taiwan Dollar', 'symbol' => 'NT$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'UAH' , 'name' => 'Hryvnia', 'symbol' => '₴' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'USD' , 'name' => 'US Dollar', 'symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'UYU' , 'name' => 'Pesos', 'symbo' => '$U', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'UZS' , 'name' => 'Uzbekistan Sum', 'symbol' => 'лв' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'VEF' , 'name' => 'Bolivar Fuerte', 'symbol' => 'Bs' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'VND' , 'name' => 'Dong', 'symbol' => '₫' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'XCD' , 'name' => 'East Caribbean Dollar', 'symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'YER' , 'name' => 'Yemeni Rial', 'symbol' => '﷼'   , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'ZAR' , 'name' => 'Rand', 'symbol' => 'R' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'AED' , 'name' => 'United Arab Emirates dirham', 'symbol' => '.إ' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'AOA' , 'name' => 'Angolan kwanza', 'symbol' => 'Kz' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'AMD' , 'name' => 'Armenian dram', 'symbol' => '֏' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'BHD' , 'name' => 'Bahraini dinar', 'symbol' => 'BD' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'BDT' , 'name' => 'Bangladeshi taka', 'symbol' => '৳' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'BIF' , 'name' => 'Burundian franc', 'symbol' => 'FBu' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'CVE' , 'name' => 'Cape Verdean escudo', 'symbol' => 'Esc' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'CF' ,  'name' => 'Comorian franc', 'symbol' => 'CF' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'DJF' , 'name' => 'Djiboutian franc', 'symbol' => 'Fdj' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'DZD' , 'name' => 'Algerian dinar', 'symbol' => 'DA' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'ERN' , 'name' => 'Eritrean nakfa', 'symbol' => 'Nkf' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'ETB' , 'name' => 'Ethiopian birr', 'symbol' => 'Br' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'GEL' , 'name' => 'Georgian lari', 'symbol' => 'ლ' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'GGP' , 'name' => 'Pounds', 'symbol' => '£' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'GHC' , 'name' => 'Cedis', 'symbol' => '¢' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'GHS' , 'name' => 'Ghanaian cedi', 'symbol' => 'GH₵' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'GMD' , 'name' => 'Gambian dalasi', 'symbol' => 'D' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'GNF' , 'name' => 'Guinean franc', 'symbol' => 'FG' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'IMP' , 'name' => 'Pounds', 'symbol' => '£' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'IQD' , 'name' => 'Iraqi dinar', 'symbol' => 'ع.د' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'JEP' , 'name' => 'Pounds', 'symbol' => '£' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'JOD' , 'name' => 'Jordanian dinar', 'symbol' => 'د.ا' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'KES' , 'name' => 'Kenyan shilling', 'symbol' => 'Ksh' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'KMF' , 'name' => 'Comorian franc', 'symbol' => 'CF' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'KWD' , 'name' => 'Kuwaiti dinar', 'symbol' => 'د.ك' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'LYD' , 'name' => 'Libyan dinar', 'symbol' => 'ل.د' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'MAD' , 'name' => 'Moroccan dirham', 'symbol' => 'MAD' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'MDL' , 'name' => 'Moldovan leu', 'symbol' => 'L' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'MGA' , 'name' => 'Malagasy ariary', 'symbol' => 'Ar' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'MMK' , 'name' => 'Myanmar kyat', 'symbol' => 'K' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'MOP' , 'name' => 'Macanese pataca', 'symbol' => 'MOP$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'MRO' , 'name' => 'Mauritanian ouguiya', 'symbol' => 'UM' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'MVR' , 'name' => 'Maldivian rufiyaa', 'symbol' => 'Rf' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'MWK' , 'name' => 'Malawian kwacha', 'symbol' => 'MK' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'NAD' , 'name' => 'Dollars', 'symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'PGK' , 'name' => 'Papua New Guinean kina', 'symbol' => 'K' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'RWF' , 'name' => 'Rwandan franc', 'symbol' => 'R₣' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'SDG' , 'name' => 'Sudanese pound', 'symbol' => 'ج.س' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'SLL' , 'name' => 'Sierra Leonean leone', 'symbol' => 'Le' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'SSP' , 'name' => 'South Sudanese pound', 'symbol' => '£' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'STD' , 'name' => 'São Tomé and Príncipe dobra', 'symbol' => 'Db' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'SZL' , 'name' => 'Swazi lilangeni', 'symbol' => 'L' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'TJS' , 'name' => 'Tajikistani somoni', 'symbol' => 'ЅM' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'TMT' , 'name' => 'Turkmenistani manat', 'symbol' => 'T' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'TND' , 'name' => 'Tunisian dinar', 'symbol' => 'DT' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'TOP' , 'name' => 'Tongan paʻanga', 'symbol' => 'T$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'TRL' , 'name' => 'Liras', 'symbol' => '£' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'TVD' , 'name' => 'Dollars', 'symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'TZS' , 'name' => 'Tanzanian shilling', 'symbol' => 'TSh' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'UGX' , 'name' => 'Ugandan shilling', 'symbol' => 'USh' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'VUV' , 'name' => 'Vanuatu vatu', 'symbol' => 'VT' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'WST' , 'name' => 'Samoan tālā', 'symbol' => 'WS$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'XAF' , 'name' => 'Central African CFA franc', 'symbol' => 'FCFA' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'XPF' , 'name' => 'CFP franc', 'symbol' => '₣' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'XOF' , 'name' => 'West African CFA franc', 'symbol' => 'CFA' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'ZMW' , 'name' => 'Zambian kwacha', 'symbol' => 'ZK' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'ZWL' , 'name' => 'Zimbabwean dollar', 'symbol' => '$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
			['currency' =>'ZWD' , 'name' => 'Zimbabwe  Dollars', 'symbol' => 'Z$' , 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
		];

		Currency::insert($currencies);
    }
}
