<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Section;

class SectionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Section::truncate();
        $data = [
        ['id' => 1, 'columnname' => 'basic_product_data' , 'displaycolumnname' => 'Basic product data', 'status' => 1 , 'section'=> 0 ,'relation' => null],           
        ['id' => 2, 'columnname' => 'price_availibility' , 'displaycolumnname' => 'Price & availability', 'status' => 1 , 'section'=> 0 ,'relation' => null],           
        ['id' => 3, 'columnname' => 'product_category' , 'displaycolumnname' => 'Product category', 'status' => 1 , 'section'=> 0 ,'relation' => null],           
        ['id' => 4, 'columnname' => 'product_identifier' , 'displaycolumnname' => 'Product identifiers', 'status' => 1 , 'section'=> 0 ,'relation' => null],           
        ['id' => 5, 'columnname' => 'detail_product_description' , 'displaycolumnname' => 'Detailed product description', 'status' => 1 , 'section'=> 0 ,'relation' => null],           
        ['id' => 6, 'columnname' => 'shopping_configuration' , 'displaycolumnname' => 'Shopping campaigns and other configurations', 'status' => 1, 'section'=> 0 ,'relation' => null],           
        ['id' => 7, 'columnname' => 'shipping' , 'displaycolumnname' => 'Shipping', 'status' => 1, 'section'=> 0 ,'relation' => null],           
        ['id' => 8, 'columnname' => 'tax' , 'displaycolumnname' => 'Tax', 'status' => 1, 'section'=> 0 ,'relation' => null],           
        ['id' => 9, 'columnname' => 'others' , 'displaycolumnname' => 'Others', 'status' => 1, 'section'=> 0 ,'relation' => null],           
        ['id' => 10, 'columnname' => 'id' , 'displaycolumnname' => 'Product Id', 'status' => 1, 'section'=> 0 ,'relation' => 1],           
        ['id' => 11, 'columnname' => 'title' , 'displaycolumnname' => 'Product Title', 'status' => 1, 'section'=> 0 ,'relation' => 1],           
        ['id' => 12, 'columnname' => 'description' , 'displaycolumnname' => 'Product Description', 'status' => 1, 'section'=> 0 ,'relation' => 1],           
        ['id' => 13, 'columnname' => 'link' , 'displaycolumnname' => 'Product URL', 'status' => 1, 'section'=> 0 ,'relation' => 1],           
        ['id' => 14, 'columnname' => 'image_link' , 'displaycolumnname' => 'Main Image', 'status' => 1, 'section'=> 0 ,'relation' => 1],           
        ['id' => 15, 'columnname' => 'mobile_link' , 'displaycolumnname' => 'Product URL', 'status' => 1, 'section'=> 0 ,'relation' => 1],           
        ['id' => 16, 'columnname' => 'images_1' , 'displaycolumnname' => 'Additional Image 1', 'status' => 1, 'section'=> 0 ,'relation' => 1],           
        ['id' => 17, 'columnname' => 'images_2' , 'displaycolumnname' => 'Additional Image 2', 'status' => 1, 'section'=> 0 ,'relation' => 1],           
        ['id' => 18, 'columnname' => 'images_3' , 'displaycolumnname' => 'Additional Image 3', 'status' => 1, 'section'=> 0 ,'relation' => 1],           
        ['id' => 19, 'columnname' => 'images_4' , 'displaycolumnname' => 'Additional Image 4', 'status' => 1, 'section'=> 0 ,'relation' => 1],           
        ['id' => 20, 'columnname' => 'images_5' , 'displaycolumnname' => 'Additional Image 5', 'status' => 1, 'section'=> 0 ,'relation' => 1],           
        ['id' => 21, 'columnname' => 'images_6' , 'displaycolumnname' => 'Additional Image 6', 'status' => 1, 'section'=> 0 ,'relation' => 1],           
        ['id' => 22, 'columnname' => 'images_7' , 'displaycolumnname' => 'Additional Image 7', 'status' => 1, 'section'=> 0 ,'relation' => 1],           
        ['id' => 23, 'columnname' => 'images_8' , 'displaycolumnname' => 'Additional Image 8', 'status' => 1, 'section'=> 0 ,'relation' => 1],           
        ['id' => 24, 'columnname' => 'images_9' , 'displaycolumnname' => 'Additional Image 9', 'status' => 1, 'section'=> 0 ,'relation' => 1],           
        ['id' => 25, 'columnname' => 'images_10' , 'displaycolumnname' => 'Additional Image 10', 'status' => 1, 'section'=> 0 ,'relation' => 1],           
        ['id' => 26, 'columnname' => 'availability' , 'displaycolumnname' => 'Stock Status', 'status' => 1, 'section'=> 0 ,'relation' => 2],           
        ['id' => 27, 'columnname' => 'availability_date' , 'displaycolumnname' => 'Availability Date', 'status' => 1, 'section'=> 0 ,'relation' => 2],           
        ['id' => 28, 'columnname' => 'expiration_date' , 'displaycolumnname' => 'Expiration Date', 'status' => 1, 'section'=> 0 ,'relation' => 2],           
        ['id' => 29, 'columnname' => 'price' , 'displaycolumnname' => 'Regular Price', 'status' => 1, 'section'=> 0 ,'relation' => 2],           
        ['id' => 30, 'columnname' => 'sale_price' , 'displaycolumnname' => 'Sale Price', 'status' => 1, 'section'=> 0 ,'relation' => 2],           
        ['id' => 31, 'columnname' => 'sale_price_effective_date' , 'displaycolumnname' => 'Sale Price Effective Date', 'status' => 1, 'section'=> 0 ,'relation' => 2],           
        ['id' => 32, 'columnname' => 'unit_pricing_measure' , 'displaycolumnname' => 'Unit Pricing Measure', 'status' => 1, 'section'=> 0 ,'relation' => 2],           
        ['id' => 33, 'columnname' => 'unit_pricing_base_measure' , 'displaycolumnname' => 'Unit Pricing Base Measure', 'status' => 1, 'section'=> 0 ,'relation' => 2],           
        ['id' => 34, 'columnname' => 'installment' , 'displaycolumnname' => 'Installment', 'status' => 1, 'section'=> 0 ,'relation' => 2],           
        ['id' => 35, 'columnname' => 'loyalty_points' , 'displaycolumnname' => 'Loyalty Points', 'status' => 1, 'section'=> 0 ,'relation' => 2],           
        ['id' => 36, 'columnname' => 'google_product_category' , 'displaycolumnname' => 'Google Product Category', 'status' => 1, 'section'=> 0 ,'relation' => 3],           
        ['id' => 37, 'columnname' => 'product_type' , 'displaycolumnname' => 'Product Categories', 'status' => 1, 'section'=> 0 ,'relation' => 3],           
        ['id' => 38, 'columnname' => 'brand' , 'displaycolumnname' => 'Manufacturer ', 'status' => 1, 'section'=> 0 ,'relation' => 4],           
        ['id' => 39, 'columnname' => 'gtin' , 'displaycolumnname' => 'GTIN', 'status' => 1, 'section'=> 0 ,'relation' => 4],           
        ['id' => 40, 'columnname' => 'mpn' , 'displaycolumnname' => 'MPN', 'status' => 1, 'section'=> 0 ,'relation' => 4],           
        ['id' => 41, 'columnname' => 'condition' , 'displaycolumnname' => 'Condition', 'status' => 1, 'section'=> 0 ,'relation' => 5],           
        ['id' => 42, 'columnname' => 'adult' , 'displaycolumnname' => 'Adult', 'status' => 1, 'section'=> 0 ,'relation' => 5],           
        ['id' => 43, 'columnname' => 'multipack' , 'displaycolumnname' => 'Multipack', 'status' => 1, 'section'=> 0 ,'relation' => 5],           
        ['id' => 44, 'columnname' => 'is_bundle' , 'displaycolumnname' => 'Is Bundle', 'status' => 1, 'section'=> 0 ,'relation' => 5],           
        ['id' => 45, 'columnname' => 'energy_efficiency_class' , 'displaycolumnname' => 'Energy Efficiency Class', 'status' => 1, 'section'=> 0 ,'relation' => 5],           
        ['id' => 46, 'columnname' => 'age_group' , 'displaycolumnname' => 'Age Group', 'status' => 1, 'section'=> 0 ,'relation' => 5],           
        ['id' => 47, 'columnname' => 'color' , 'displaycolumnname' => 'Color', 'status' => 1, 'section'=> 0 ,'relation' => 5],           
        ['id' => 48, 'columnname' => 'gender' , 'displaycolumnname' => 'Gender', 'status' => 1, 'section'=> 0 ,'relation' => 5],           
        ['id' => 49, 'columnname' => 'material' , 'displaycolumnname' => 'Material', 'status' => 1, 'section'=> 0 ,'relation' => 5],           
        ['id' => 50, 'columnname' => 'pattern' , 'displaycolumnname' => 'Pattern', 'status' => 1, 'section'=> 0 ,'relation' => 5],           
        ['id' => 51, 'columnname' => 'size' , 'displaycolumnname' => 'Size of the item', 'status' => 1, 'section'=> 0 ,'relation' => 5],           
        ['id' => 52, 'columnname' => 'size_type' , 'displaycolumnname' => 'Size Type', 'status' => 1, 'section'=> 0 ,'relation' => 5],           
        ['id' => 53, 'columnname' => 'size_system' , 'displaycolumnname' => 'Size System', 'status' => 1, 'section'=> 0 ,'relation' => 5],           
        ['id' => 54, 'columnname' => 'item_group_id' , 'displaycolumnname' => 'Item Group Id', 'status' => 1, 'section'=> 0 ,'relation' => 5],           
        ['id' => 55, 'columnname' => 'adwords_redirect' , 'displaycolumnname' => 'Adwords Redirect', 'status' => 1, 'section'=> 0 ,'relation' => 6],           
        ['id' => 56, 'columnname' => 'excluded_destination' , 'displaycolumnname' => 'Excluded Destination', 'status' => 1, 'section'=> 0 ,'relation' => 6],           
        ['id' => 57, 'columnname' => 'custom_label_0' , 'displaycolumnname' => 'Custom label 0', 'status' => 1, 'section'=> 0 ,'relation' => 6],           
        ['id' => 58, 'columnname' => 'custom_label_1' , 'displaycolumnname' => 'Custom label 1', 'status' => 1, 'section'=> 0 ,'relation' => 6],           
        ['id' => 59, 'columnname' => 'custom_label_2' , 'displaycolumnname' => 'Custom label 2', 'status' => 1, 'section'=> 0 ,'relation' => 6],           
        ['id' => 60, 'columnname' => 'custom_label_3' , 'displaycolumnname' => 'Custom label 3', 'status' => 1, 'section'=> 0 ,'relation' => 6],           
        ['id' => 61, 'columnname' => 'custom_label_4' , 'displaycolumnname' => 'Custom label 4', 'status' => 1, 'section'=> 0 ,'relation' => 6],           
        ['id' => 62, 'columnname' => 'promotion_id' , 'displaycolumnname' => 'Promotion Id', 'status' => 1, 'section'=> 0 ,'relation' => 6],           
        ['id' => 63, 'columnname' => 'shipping' , 'displaycolumnname' => 'Shipping', 'status' => 1, 'section'=> 0 ,'relation' => 7],           
        ['id' => 64, 'columnname' => 'shipping_label' , 'displaycolumnname' => 'Shipping Label', 'status' => 1, 'section'=> 0 ,'relation' => 7],           
        ['id' => 65, 'columnname' => 'shipping_weight' , 'displaycolumnname' => 'Shipping Weight', 'status' => 1, 'section'=> 0 ,'relation' => 7],           
        ['id' => 66, 'columnname' => 'shipping_length' , 'displaycolumnname' => 'Shipping Length', 'status' => 1, 'section'=> 0 ,'relation' => 7],           
        ['id' => 67, 'columnname' => 'shipping_width' , 'displaycolumnname' => 'Shipping Width', 'status' => 1, 'section'=> 0 ,'relation' => 7],           
        ['id' => 68, 'columnname' => 'shipping_height' , 'displaycolumnname' => 'Shipping Height', 'status' => 1, 'section'=> 0 ,'relation' => 7],           
        ['id' => 69, 'columnname' => 'tax' , 'displaycolumnname' => 'Tax', 'status' => 1, 'section'=> 0 ,'relation' => 8],           
        ['id' => 70, 'columnname' => 'store_code' , 'displaycolumnname' => 'Store code', 'status' => 1, 'section'=> 0 ,'relation' => 9],           
        ['id' => 71, 'columnname' => 'quantity' , 'displaycolumnname' => 'Quantity', 'status' => 1, 'section'=> 0 ,'relation' => 9],           
        ['id' => 72, 'columnname' => 'pickup_method' , 'displaycolumnname' => 'Pickup method', 'status' => 1, 'section'=> 0 ,'relation' => 9],           
        ['id' => 73, 'columnname' => 'pickup_sla' , 'displaycolumnname' => 'Pickup Sla', 'status' => 1, 'section'=> 0 ,'relation' => 9],           
        ['id' => 74, 'columnname' => 'id' , 'displaycolumnname' => 'Product Id', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 75, 'columnname' => 'product_type_id' , 'displaycolumnname' => 'Product Type', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 76, 'columnname' => 'vendor_id' , 'displaycolumnname' => 'Vendor', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 77, 'columnname' => 'weight_type_id' , 'displaycolumnname' => 'Weight Type', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 78, 'columnname' => 'title' , 'displaycolumnname' => 'Product Title', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 79, 'columnname' => 'slug' , 'displaycolumnname' => 'Product Link', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 80, 'columnname' => 'description' , 'displaycolumnname' => 'Product Description', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 81, 'columnname' => 'status' , 'displaycolumnname' => 'Product Status', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 82, 'columnname' => 'schedule_time' , 'displaycolumnname' => 'Schedule Time', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 83, 'columnname' => 'price' , 'displaycolumnname' => 'Sale Price', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 84, 'columnname' => 'compare_at_price' , 'displaycolumnname' => 'Regular Price', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 85, 'columnname' => 'cost_per_item' , 'displaycolumnname' => 'Cost Per Item', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 86, 'columnname' => 'is_product_charge' , 'displaycolumnname' => 'Is Product Charge', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 87, 'columnname' => 'sku' , 'displaycolumnname' => 'SKU', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 88, 'columnname' => 'barcode' , 'displaycolumnname' => 'Barcode', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 89, 'columnname' => 'quantity' , 'displaycolumnname' => 'Quantity', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 90, 'columnname' => 'is_track' , 'displaycolumnname' => 'Is Track', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 91, 'columnname' => 'is_continue_selling' , 'displaycolumnname' => 'Is Continue Selling', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 92, 'columnname' => 'is_pysical_product' , 'displaycolumnname' => 'Is Physical Product', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 93, 'columnname' => 'weight' , 'displaycolumnname' => 'Weight', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 94, 'columnname' => 'hs_code' , 'displaycolumnname' => 'HS Code', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 95, 'columnname' => 'min_order_limit' , 'displaycolumnname' => 'Min Order', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 96, 'columnname' => 'max_order_limit' , 'displaycolumnname' => 'Max Order', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 97, 'columnname' => 'is_cod_enabled' , 'displaycolumnname' => 'COD Available', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 98, 'columnname' => 'is_size_chart_enabled' , 'displaycolumnname' => 'Size chart', 'status' => 1, 'section' => 1, 'relation' => null],
        ['id' => 99, 'columnname' => 'group_id' , 'displaycolumnname' => 'Parent Id', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 100, 'columnname' => 'is_special_product' , 'displaycolumnname' => 'Special Product', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 101, 'columnname' => 'special_price' , 'displaycolumnname' => 'Special Price', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 102, 'columnname' => 'expiry_date' , 'displaycolumnname' => 'Expiry Date', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 103, 'columnname' => 'special_product_status' , 'displaycolumnname' => 'Special Product', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 104, 'columnname' => 'seo_title' , 'displaycolumnname' => 'SEO Title', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 105, 'columnname' => 'seo_description' , 'displaycolumnname' => 'SEO Description', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 106, 'columnname' => 'stock' , 'displaycolumnname' => 'Stock', 'status' => 1, 'section' => 1, 'relation' => null],
        ['id' => 107, 'columnname' => 'is_gift_card' , 'displaycolumnname' => 'Is Giftcard', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 108, 'columnname' => 'collection' , 'displaycolumnname' => 'Product Local Category', 'status' => 1, 'section' => 1, 'relation' => null],           
        ['id' => 109, 'columnname' => 'product_image' , 'displaycolumnname' => 'Product Image', 'status' => 1, 'section' => 1, 'relation' => null],
        ['id' => 110, 'columnname' => 'url' , 'displaycolumnname' => 'Product URL', 'status' => 1, 'section' => 1, 'relation' => null],
        ['id' => 111, 'columnname' => 'main_image' , 'displaycolumnname' => 'Main Image', 'status' => 1, 'section' => 1, 'relation' => null],
        ['id' => 112, 'columnname' => 'google_product_category' , 'displaycolumnname' => 'Google Product Category', 'status' => 1, 'section' => 1, 'relation' => null],
        ['id' => 113, 'columnname' => 'condition' , 'displaycolumnname' => 'Condition', 'status' => 1, 'section' => 1, 'relation' => null],
        ['id' => 114, 'columnname' => 'adult' , 'displaycolumnname' => 'Adult', 'status' => 1, 'section' => 1, 'relation' => null],
        
        

        ];
        Section::insert($data);
    }
}
